model:
  name: "CNNPyramidTransformerSeg"
  in_channels: 1
  num_classes: 3
  encoder_channels: [64, 128, 256, 512]
  encoder_blocks: [2, 2, 2, 2]
  dropout: 0.1
  bottleneck:
    type: "PyramidTransformerBottleneck"
    embed_dim: 256
    ppm_pool_sizes: [1, 2, 4, 8]
    num_heads: 8
    transformer_depth: 4
    ffn_dim: 1024
    dropout: 0.1
  decoder_channels: [256, 128, 64, 32]
  deep_supervision: false
